version: '3.9'
services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '10100:6379'
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - '10110:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres