export enum IntegrationType {
  CHAT = 'CHAT',
  SOURCE_CONTROL = 'SOURCE_CONTROL',
  CLOUD_PROVIDER = 'CLOUD_PROVIDER',
  ISSUE_TRACKER = 'ISSUE_TRACKER',
  DEPLOYMENT = 'DEPLOYMENT',
  MONITORING = 'MONITORING',
  NOTIFICATION = 'NOTIFICATION',
}
