export enum ProjectState {
  DRAFT = 'DRAFT',
  PENDING_OF_COMPLETE_INTEGRATIONS = 'PENDING_OF_COMPLETE_INTEGRATIONS',
  READY_TO_CREATE = 'READY_TO_CREATE',
  REPOSITORY_CREATED = 'REPOSITORY_CREATED',
  CI_CD_JOB_CREATED = 'CI_CD_JOB_CREATED',
  CLOUD_INFRA_CREATED = 'CLOUD_INFRA_CREATED',
  CREATED = 'CREATED',
  ERROR = 'ERROR',
}
