export enum Configuration {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  NODE_NAME = 'NODE_NAME',
  MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING',
  REDIS_CONNECTION_STRING = 'REDIS_CONNECTION_STRING',
  GH_APP_NAME = 'GH_APP_NAME',
  GH_APP_URL = 'GH_APP_URL',
}
