name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-2'
      SOURCE_DIR: 'kimos-api.zip'
      DEST_DIR: 'kimos-api.zip'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create ZIP archive
        run: |
          cd $SOURCE_DIR
          zip -r $GITHUB_WORKSPACE/kimos-api.zip .

      - name: Deploy ZIP to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          manifest: '{"aws-access-key-id": "${{ secrets.AWS_ACCESS_KEY_ID }}", "aws-secret-access-key": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "aws-region": "${{ env.AWS_REGION }}", "source": "${{ env.SOURCE_DIR }}", "destination": "${{ env.DEST_DIR }}", "cache-control": "max-age=3600"}'
          upload-zip: true
          zip-name: 'kimos-api.zip'